TRACK_MAP = {
    0: 'Melbourne',
    1: 'Paul Ricard',
    2: 'Shangai',
    3: 'Bahrain',
    4: 'Barcelona',
    5: 'Monaco',
    6: 'Montreal',
    7: 'Silverstone',
    8: 'Hockenheim',
    9: 'Hungaroring',
    10: 'Spa-Francorchamps',
    11: 'Monza',
    12: 'Singapore',
    13: 'Suzuka',
    14: 'Abu Dhabi',
    15: 'Texas',
    16: 'Brazil',
    17: 'Redbull Ring',
    18: 'Sochi',
    19: 'Mexico',
    20: 'Baku',
    21: 'Bahrain Short',
    22: 'Silverstone Short',
    23: 'Texas Short',
    24: 'Suzuka Short'
}